const pokedex = [
    { 
        id: 1,
        nombre: "Bulbasaur",
        tipo1: "Planta",
        tipo2: "Veneno",
        color: "Verde",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 2,
        nombre: "Ivysaur",
        tipo1: "Planta",
        tipo2: "Veneno",
        color: "Verde",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 3,
        nombre: "Venusaur",
        tipo1: "Planta",
        tipo2: "Veneno",
        color: "Verde",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 4,
        nombre: "Charmander",
        tipo1: "Fuego",
        tipo2: "",
        color: "Naranja",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 5,
        nombre: "Charmeleon",
        tipo1: "Fuego",
        tipo2: "",
        color: "Rojo",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 6,
        nombre: "Charizard",
        tipo1: "Fuego",
        tipo2: "Volador",
        color: "Naranja",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 7,
        nombre: "Squirtle",
        tipo1: "Agua",
        tipo2: "",
        color: "Azul",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 8,
        nombre: "Wartortle",
        tipo1: "Agua",
        tipo2: "",
        color: "Azul",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 9,
        nombre: "Blastoise",
        tipo1: "Agua",
        tipo2: "",
        color: "Azul",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 10,
        nombre: "Caterpie",
        tipo1: "Bicho",
        tipo2: "",
        color: "Verde",
        patas: 8,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 11,
        nombre: "Metapod",
        tipo1: "Bicho",
        tipo2: "",
        color: "Verde",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 12,
        nombre: "Butterfree",
        tipo1: "Bicho",
        tipo2: "Volador",
        color: "Blanco",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 13,
        nombre: "Weedle",
        tipo1: "Bicho",
        tipo2: "Veneno",
        color: "Marrón",
        patas: 6,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 14,
        nombre: "Kakuna",
        tipo1: "Bicho",
        tipo2: "Veneno",
        color: "Amarillo",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 15,
        nombre: "Beedrill",
        tipo1: "Bicho",
        tipo2: "Veneno",
        color: "Amarillo",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 16,
        nombre: "Pidgey",
        tipo1: "Normal",
        tipo2: "Volador",
        color: "Marrón",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 17,
        nombre: "Pidgeotto",
        tipo1: "Normal",
        tipo2: "Volador",
        color: "Marrón",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 18,
        nombre: "Pidgeot",
        tipo1: "Normal",
        tipo2: "Volador",
        color: "Marrón",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 19,
        nombre: "Rattata",
        tipo1: "Normal",
        tipo2: "",
        color: "Morado",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 20,
        nombre: "Raticate",
        tipo1: "Normal",
        tipo2: "",
        color: "Marrón",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 21,
        nombre: "Spearow",
        tipo1: "Normal",
        tipo2: "Volador",
        color: "Marrón",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 22,
        nombre: "Fearow",
        tipo1: "Normal",
        tipo2: "Volador",
        color: "Marrón",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 23,
        nombre: "Ekans",
        tipo1: "Veneno",
        tipo2: "",
        color: "Morado",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 24,
        nombre: "Arbok",
        tipo1: "Veneno",
        tipo2: "",
        color: "Morado",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 25,
        nombre: "Pikachu",
        tipo1: "Eléctrico",
        tipo2: "",
        color: "Amarillo",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 26,
        nombre: "Raichu",
        tipo1: "Eléctrico",
        tipo2: "",
        color: "Naranja",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 27,
        nombre: "Sandshrew",
        tipo1: "Tierra",
        tipo2: "",
        color: "Amarillo",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 28,
        nombre: "Sandslash",
        tipo1: "Tierra",
        tipo2: "",
        color: "Amarillo",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 29,
        nombre: "Nidoran♀",
        tipo1: "Veneno",
        tipo2: "",
        color: "Azul",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 30,
        nombre: "Nidorina",
        tipo1: "Veneno",
        tipo2: "",
        color: "Azul",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 31,
        nombre: "Nidoqueen",
        tipo1: "Veneno",
        tipo2: "Tierra",
        color: "Azul",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 32,
        nombre: "Nidoran♂",
        tipo1: "Veneno",
        tipo2: "",
        color: "Morado",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 33,
        nombre: "Nidorino",
        tipo1: "Veneno",
        tipo2: "",
        color: "Morado",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 34,
        nombre: "Nidoking",
        tipo1: "Veneno",
        tipo2: "Tierra",
        color: "Morado",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 35,
        nombre: "Clefairy",
        tipo1: "Hada",
        tipo2: "",
        color: "Rosa",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 36,
        nombre: "Clefable",
        tipo1: "Hada",
        tipo2: "",
        color: "Rosa",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 37,
        nombre: "Vulpix",
        tipo1: "Fuego",
        tipo2: "",
        color: "Marrón",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 38,
        nombre: "Ninetales",
        tipo1: "Fuego",
        tipo2: "",
        color: "Amarillo",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 39,
        nombre: "Jigglypuff",
        tipo1: "Normal",
        tipo2: "Hada",
        color: "Rosa",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 40,
        nombre: "Wigglytuff",
        tipo1: "Normal",
        tipo2: "Hada",
        color: "Rosa",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 41,
        nombre: "Zubat",
        tipo1: "Veneno",
        tipo2: "Volador",
        color: "Morado",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 42,
        nombre: "Golbat",
        tipo1: "Veneno",
        tipo2: "Volador",
        color: "Morado",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 43,
        nombre: "Oddish",
        tipo1: "Planta",
        tipo2: "Veneno",
        color: "Azul",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 44,
        nombre: "Gloom",
        tipo1: "Planta",
        tipo2: "Veneno",
        color: "Azul",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 45,
        nombre: "Vileplume",
        tipo1: "Planta",
        tipo2: "Veneno",
        color: "Rojo",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 46,
        nombre: "Paras",
        tipo1: "Bicho",
        tipo2: "Planta",
        color: "Naranja",
        patas: 6,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 47,
        nombre: "Parasect",
        tipo1: "Bicho",
        tipo2: "Planta",
        color: "Rojo",
        patas: 6,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 48,
        nombre: "Venonat",
        tipo1: "Bicho",
        tipo2: "Veneno",
        color: "Morado",
        patas: 6,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 49,
        nombre: "Venomoth",
        tipo1: "Bicho",
        tipo2: "Veneno",
        color: "Morado",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 50,
        nombre: "Diglett",
        tipo1: "Tierra",
        tipo2: "",
        color: "Marrón",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,
        id: 51,
        nombre: "Dugtrio",
        tipo1: "Tierra",
        tipo2: "",
        color: "Marrón",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 52,
        nombre: "Meowth",
        tipo1: "Normal",
        tipo2: "",
        color: "Amarillo",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 53,
        nombre: "Persian",
        tipo1: "Normal",
        tipo2: "",
        color: "Amarillo",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 54,
        nombre: "Psyduck",
        tipo1: "Agua",
        tipo2: "",
        color: "Amarillo",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 55,
        nombre: "Golduck",
        tipo1: "Agua",
        tipo2: "",
        color: "Azul",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 56,
        nombre: "Mankey",
        tipo1: "Lucha",
        tipo2: "",
        color: "Marrón",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 57,
        nombre: "Primeape",
        tipo1: "Lucha",
        tipo2: "",
        color: "Marrón",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 58,
        nombre: "Growlithe",
        tipo1: "Fuego",
        tipo2: "",
        color: "Naranja",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 59,
        nombre: "Arcanine",
        tipo1: "Fuego",
        tipo2: "",
        color: "Naranja",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 60,
        nombre: "Poliwag",
        tipo1: "Agua",
        tipo2: "",
        color: "Azul",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 61,
        nombre: "Poliwhirl",
        tipo1: "Agua",
        tipo2: "",
        color: "Azul",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 62,
        nombre: "Poliwrath",
        tipo1: "Agua",
        tipo2: "Lucha",
        color: "Azul",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 63,
        nombre: "Abra",
        tipo1: "Psíquico",
        tipo2: "",
        color: "Marrón",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 64,
        nombre: "Kadabra",
        tipo1: "Psíquico",
        tipo2: "",
        color: "Amarillo",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 65,
        nombre: "Alakazam",
        tipo1: "Psíquico",
        tipo2: "",
        color: "Amarillo",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 66,
        nombre: "Machop",
        tipo1: "Lucha",
        tipo2: "",
        color: "Gris",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 67,
        nombre: "Machoke",
        tipo1: "Lucha",
        tipo2: "",
        color: "Gris",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 68,
        nombre: "Machamp",
        tipo1: "Lucha",
        tipo2: "",
        color: "Gris",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 69,
        nombre: "Bellsprout",
        tipo1: "Planta",
        tipo2: "Veneno",
        color: "Verde",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 70,
        nombre: "Weepinbell",
        tipo1: "Planta",
        tipo2: "Veneno",
        color: "Verde",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 71,
        nombre: "Victreebel",
        tipo1: "Planta",
        tipo2: "Veneno",
        color: "Verde",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 72,
        nombre: "Tentacool",
        tipo1: "Agua",
        tipo2: "Veneno",
        color: "Azul",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 73,
        nombre: "Tentacruel",
        tipo1: "Agua",
        tipo2: "Veneno",
        color: "Azul",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 74,
        nombre: "Geodude",
        tipo1: "Roca",
        tipo2: "Tierra",
        color: "Marrón",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 75,
        nombre: "Graveler",
        tipo1: "Roca",
        tipo2: "Tierra",
        color: "Marrón",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 76,
        nombre: "Golem",
        tipo1: "Roca",
        tipo2: "Tierra",
        color: "Marrón",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 77,
        nombre: "Ponyta",
        tipo1: "Fuego",
        tipo2: "",
        color: "Amarillo",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 78,
        nombre: "Rapidash",
        tipo1: "Fuego",
        tipo2: "",
        color: "Amarillo",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 79,
        nombre: "Slowpoke",
        tipo1: "Agua",
        tipo2: "Psíquico",
        color: "Rosa",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 80,
        nombre: "Slowbro",
        tipo1: "Agua",
        tipo2: "Psíquico",
        color: "Rosa",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 81,
        nombre: "Magnemite",
        tipo1: "Eléctrico",
        tipo2: "Acero",
        color: "Gris",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 82,
        nombre: "Magneton",
        tipo1: "Eléctrico",
        tipo2: "Acero",
        color: "Gris",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 83,
        nombre: "Farfetch'd",
        tipo1: "Normal",
        tipo2: "Volador",
        color: "Marrón",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 84,
        nombre: "Doduo",
        tipo1: "Normal",
        tipo2: "Volador",
        color: "Marrón",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 85,
        nombre: "Dodrio",
        tipo1: "Normal",
        tipo2: "Volador",
        color: "Marrón",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 86,
        nombre: "Seel",
        tipo1: "Agua",
        tipo2: "",
        color: "Blanco",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 87,
        nombre: "Dewgong",
        tipo1: "Agua",
        tipo2: "Hielo",
        color: "Blanco",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 88,
        nombre: "Grimer",
        tipo1: "Veneno",
        tipo2: "",
        color: "Morado",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 89,
        nombre: "Muk",
        tipo1: "Veneno",
        tipo2: "",
        color: "Morado",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 90,
        nombre: "Shellder",
        tipo1: "Agua",
        tipo2: "",
        color: "Morado",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 91,
        nombre: "Cloyster",
        tipo1: "Agua",
        tipo2: "Hielo",
        color: "Morado",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 92,
        nombre: "Gastly",
        tipo1: "Fantasma",
        tipo2: "Veneno",
        color: "Morado",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 93,
        nombre: "Haunter",
        tipo1: "Fantasma",
        tipo2: "Veneno",
        color: "Morado",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 94,
        nombre: "Gengar",
        tipo1: "Fantasma",
        tipo2: "Veneno",
        color: "Morado",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 95,
        nombre: "Onix",
        tipo1: "Roca",
        tipo2: "Tierra",
        color: "Gris",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 96,
        nombre: "Drowzee",
        tipo1: "Psíquico",
        tipo2: "",
        color: "Amarillo",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 97,
        nombre: "Hypno",
        tipo1: "Psíquico",
        tipo2: "",
        color: "Amarillo",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 98,
        nombre: "Krabby",
        tipo1: "Agua",
        tipo2: "",
        color: "Rojo",
        patas: 6,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 99,
        nombre: "Kingler",
        tipo1: "Agua",
        tipo2: "",
        color: "Rojo",
        patas: 6,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 100,
        nombre: "Voltorb",
        tipo1: "Eléctrico",
        tipo2: "",
        color: "Rojo",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,
        id: 101,
        nombre: "Electrode",
        tipo1: "Eléctrico",
        tipo2: "",
        color: "Rojo",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 102,
        nombre: "Exeggcute",
        tipo1: "Planta",
        tipo2: "Psíquico",
        color: "Rosa",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 103,
        nombre: "Exeggutor",
        tipo1: "Planta",
        tipo2: "Psíquico",
        color: "Amarillo",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 104,
        nombre: "Cubone",
        tipo1: "Tierra",
        tipo2: "",
        color: "Marrón",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 105,
        nombre: "Marowak",
        tipo1: "Tierra",
        tipo2: "",
        color: "Marrón",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 106,
        nombre: "Hitmonlee",
        tipo1: "Lucha",
        tipo2: "",
        color: "Marrón",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 107,
        nombre: "Hitmonchan",
        tipo1: "Lucha",
        tipo2: "",
        color: "Marrón",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 108,
        nombre: "Lickitung",
        tipo1: "Normal",
        tipo2: "",
        color: "Rosa",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 109,
        nombre: "Koffing",
        tipo1: "Veneno",
        tipo2: "",
        color: "Morado",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 110,
        nombre: "Weezing",
        tipo1: "Veneno",
        tipo2: "",
        color: "Morado",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 111,
        nombre: "Rhyhorn",
        tipo1: "Tierra",
        tipo2: "Roca",
        color: "Gris",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 112,
        nombre: "Rhydon",
        tipo1: "Tierra",
        tipo2: "Roca",
        color: "Gris",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 113,
        nombre: "Chansey",
        tipo1: "Normal",
        tipo2: "",
        color: "Rosa",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 114,
        nombre: "Tangela",
        tipo1: "Planta",
        tipo2: "",
        color: "Azul",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 115,
        nombre: "Kangaskhan",
        tipo1: "Normal",
        tipo2: "",
        color: "Marrón",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 116,
        nombre: "Horsea",
        tipo1: "Agua",
        tipo2: "",
        color: "Azul",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 117,
        nombre: "Seadra",
        tipo1: "Agua",
        tipo2: "",
        color: "Azul",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 118,
        nombre: "Goldeen",
        tipo1: "Agua",
        tipo2: "",
        color: "Blanco",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 119,
        nombre: "Seaking",
        tipo1: "Agua",
        tipo2: "",
        color: "Naranja",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 120,
        nombre: "Staryu",
        tipo1: "Agua",
        tipo2: "",
        color: "Marrón",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 121,
        nombre: "Starmie",
        tipo1: "Agua",
        tipo2: "Psíquico",
        color: "Morado",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 122,
        nombre: "Mr. Mime",
        tipo1: "Psíquico",
        tipo2: "Hada",
        color: "Rosa",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 123,
        nombre: "Scyther",
        tipo1: "Bicho",
        tipo2: "Volador",
        color: "Verde",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 124,
        nombre: "Jynx",
        tipo1: "Hielo",
        tipo2: "Psíquico",
        color: "Morado",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 125,
        nombre: "Electabuzz",
        tipo1: "Eléctrico",
        tipo2: "",
        color: "Amarillo",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 126,
        nombre: "Magmar",
        tipo1: "Fuego",
        tipo2: "",
        color: "Rojo",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 127,
        nombre: "Pinsir",
        tipo1: "Bicho",
        tipo2: "",
        color: "Marrón",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 128,
        nombre: "Tauros",
        tipo1: "Normal",
        tipo2: "",
        color: "Marrón",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 129,
        nombre: "Magikarp",
        tipo1: "Agua",
        tipo2: "",
        color: "Rojo",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 130,
        nombre: "Gyarados",
        tipo1: "Agua",
        tipo2: "Volador",
        color: "Azul",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 131,
        nombre: "Lapras",
        tipo1: "Agua",
        tipo2: "Hielo",
        color: "Azul",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 132,
        nombre: "Ditto",
        tipo1: "Normal",
        tipo2: "",
        color: "Morado",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 133,
        nombre: "Eevee",
        tipo1: "Normal",
        tipo2: "",
        color: "Marrón",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 4,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 134,
        nombre: "Vaporeon",
        tipo1: "Agua",
        tipo2: "",
        color: "Azul",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 4,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 135,
        nombre: "Jolteon",
        tipo1: "Eléctrico",
        tipo2: "",
        color: "Amarillo",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 4,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 136,
        nombre: "Flareon",
        tipo1: "Fuego",
        tipo2: "",
        color: "Naranja",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 4,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 137,
        nombre: "Porygon",
        tipo1: "Normal",
        tipo2: "",
        color: "Rosa",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 138,
        nombre: "Omanyte",
        tipo1: "Roca",
        tipo2: "Agua",
        color: "Azul",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 139,
        nombre: "Omastar",
        tipo1: "Roca",
        tipo2: "Agua",
        color: "Azul",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 140,
        nombre: "Kabuto",
        tipo1: "Roca",
        tipo2: "Agua",
        color: "Marrón",
        patas: 4,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 141,
        nombre: "Kabutops",
        tipo1: "Roca",
        tipo2: "Agua",
        color: "Marrón",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 2,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 142,
        nombre: "Aerodactyl",
        tipo1: "Roca",
        tipo2: "Volador",
        color: "Morado",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 143,
        nombre: "Snorlax",
        tipo1: "Normal",
        tipo2: "",
        color: "Negro",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 144,
        nombre: "Articuno",
        tipo1: "Hielo",
        tipo2: "Volador",
        color: "Azul",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: true,

        id: 145,
        nombre: "Zapdos",
        tipo1: "Eléctrico",
        tipo2: "Volador",
        color: "Amarillo",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: true,

        id: 146,
        nombre: "Moltres",
        tipo1: "Fuego",
        tipo2: "Volador",
        color: "Amarillo",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: true,

        id: 147,
        nombre: "Dratini",
        tipo1: "Dragón",
        tipo2: "",
        color: "Azul",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 1,
        legendario: false,

        id: 148,
        nombre: "Dragonair",
        tipo1: "Dragón",
        tipo2: "",
        color: "Azul",
        patas: 0,
        alas: 0,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 2,
        legendario: false,

        id: 149,
        nombre: "Dragonite",
        tipo1: "Dragón",
        tipo2: "Volador",
        color: "Naranja",
        patas: 2,
        alas: 2,
        numeroDeEvoluciones: 3,
        posLineaEvolutiva: 3,
        legendario: false,

        id: 150,
        nombre: "Mewtwo",
        tipo1: "Psíquico",
        tipo2: "",
        color: "Morado",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: true,

        id: 151,
        nombre: "Mew",
        tipo1: "Psíquico",
        tipo2: "",
        color: "Rosa",
        patas: 2,
        alas: 0,
        numeroDeEvoluciones: 1,
        posLineaEvolutiva: 1,
        legendario: true,
    },
];

const preguntas = [
    { texto: "¿Es legendario?", filtro: (p, r) => r ? p.legendario : !p.legendario },
    
    { texto: "¿Tiene alas?", filtro: (p, r) => r ? p.alas > 0 : p.alas === 0 },
    { texto: "¿Tiene patas?", filtro: (p, r) => r ? p.patas > 0 : p.patas === 0 },
    { texto: "¿Tiene 4 patas?", filtro: (p, r) => r ? p.patas === 4 : p.patas !== 4 },
    
    { texto: "¿Tiene evoluciones?", filtro: (p, r) => r ? p.numeroDeEvoluciones > 1 : p.numeroDeEvoluciones === 1 },
    { texto: "¿Es la forma base?", filtro: (p, r) => r ? p.posLineaEvolutiva === 1 : p.posLineaEvolutiva !== 1 },
    { texto: "¿Es la forma final?", filtro: (p, r) => r ? p.posLineaEvolutiva === p.numeroDeEvoluciones : p.posLineaEvolutiva !== p.numeroDeEvoluciones },
    
    { texto: "¿Es de tipo Fuego?", filtro: (p, r) => r ? p.tipo1 === "Fuego" || p.tipo2 === "Fuego" : p.tipo1 !== "Fuego" && p.tipo2 !== "Fuego" },
    { texto: "¿Es de tipo Agua?", filtro: (p, r) => r ? p.tipo1 === "Agua" || p.tipo2 === "Agua" : p.tipo1 !== "Agua" && p.tipo2 !== "Agua" },
    { texto: "¿Es de tipo Planta?", filtro: (p, r) => r ? p.tipo1 === "Planta" || p.tipo2 === "Planta" : p.tipo1 !== "Planta" && p.tipo2 !== "Planta" },
    { texto: "¿Es de tipo Eléctrico?", filtro: (p, r) => r ? p.tipo1 === "Eléctrico" || p.tipo2 === "Eléctrico" : p.tipo1 !== "Eléctrico" && p.tipo2 !== "Eléctrico" },
    { texto: "¿Es de tipo Psíquico?", filtro: (p, r) => r ? p.tipo1 === "Psíquico" || p.tipo2 === "Psíquico" : p.tipo1 !== "Psíquico" && p.tipo2 !== "Psíquico" },
    { texto: "¿Es de tipo Normal?", filtro: (p, r) => r ? p.tipo1 === "Normal" || p.tipo2 === "Normal" : p.tipo1 !== "Normal" && p.tipo2 !== "Normal" },
    { texto: "¿Es de tipo Veneno?", filtro: (p, r) => r ? p.tipo1 === "Veneno" || p.tipo2 === "Veneno" : p.tipo1 !== "Veneno" && p.tipo2 !== "Veneno" },
    { texto: "¿Es de tipo Volador?", filtro: (p, r) => r ? p.tipo1 === "Volador" || p.tipo2 === "Volador" : p.tipo1 !== "Volador" && p.tipo2 !== "Volador" },
    { texto: "¿Es de tipo Bicho?", filtro: (p, r) => r ? p.tipo1 === "Bicho" || p.tipo2 === "Bicho" : p.tipo1 !== "Bicho" && p.tipo2 !== "Bicho" },
    { texto: "¿Es de tipo Tierra?", filtro: (p, r) => r ? p.tipo1 === "Tierra" || p.tipo2 === "Tierra" : p.tipo1 !== "Tierra" && p.tipo2 !== "Tierra" },
    { texto: "¿Es de tipo Roca?", filtro: (p, r) => r ? p.tipo1 === "Roca" || p.tipo2 === "Roca" : p.tipo1 !== "Roca" && p.tipo2 !== "Roca" },
    { texto: "¿Es de tipo Hielo?", filtro: (p, r) => r ? p.tipo1 === "Hielo" || p.tipo2 === "Hielo" : p.tipo1 !== "Hielo" && p.tipo2 !== "Hielo" },
    { texto: "¿Es de tipo Fantasma?", filtro: (p, r) => r ? p.tipo1 === "Fantasma" || p.tipo2 === "Fantasma" : p.tipo1 !== "Fantasma" && p.tipo2 !== "Fantasma" },
    { texto: "¿Es de tipo Lucha?", filtro: (p, r) => r ? p.tipo1 === "Lucha" || p.tipo2 === "Lucha" : p.tipo1 !== "Lucha" && p.tipo2 !== "Lucha" },
    { texto: "¿Es de tipo Dragón?", filtro: (p, r) => r ? p.tipo1 === "Dragón" || p.tipo2 === "Dragón" : p.tipo1 !== "Dragón" && p.tipo2 !== "Dragón" },
    { texto: "¿Es de tipo Hada?", filtro: (p, r) => r ? p.tipo1 === "Hada" || p.tipo2 === "Hada" : p.tipo1 !== "Hada" && p.tipo2 !== "Hada" },
    { texto: "¿Es de tipo Acero?", filtro: (p, r) => r ? p.tipo1 === "Acero" || p.tipo2 === "Acero" : p.tipo1 !== "Acero" && p.tipo2 !== "Acero" },

    { texto: "¿Es de color Rojo?", filtro: (p, r) => r ? p.color === "Rojo" : p.color !== "Rojo" },
    { texto: "¿Es de color Azul?", filtro: (p, r) => r ? p.color === "Azul" : p.color !== "Azul" },
    { texto: "¿Es de color Amarillo?", filtro: (p, r) => r ? p.color === "Amarillo" : p.color !== "Amarillo" },
    { texto: "¿Es de color Verde?", filtro: (p, r) => r ? p.color === "Verde" : p.color !== "Verde" },
    { texto: "¿Es de color Naranja?", filtro: (p, r) => r ? p.color === "Naranja" : p.color !== "Naranja" },
    { texto: "¿Es de color Morado?", filtro: (p, r) => r ? p.color === "Morado" : p.color !== "Morado" },
    { texto: "¿Es de color Rosa?", filtro: (p, r) => r ? p.color === "Rosa" : p.color !== "Rosa" },
    { texto: "¿Es de color Blanco?", filtro: (p, r) => r ? p.color === "Blanco" : p.color !== "Blanco" },
    { texto: "¿Es de color Marrón?", filtro: (p, r) => r ? p.color === "Marrón" : p.color !== "Marrón" },
    { texto: "¿Es de color Gris?", filtro: (p, r) => r ? p.color === "Gris" : p.color !== "Gris" },
    { texto: "¿Es de color Negro?", filtro: (p, r) => r ? p.color === "Negro" : p.color !== "Negro" },
];

// Variables de estado y referencias al DOM
let candidatos = [...pokedex];
let preguntaIndex = 0;

const questionText = document.getElementById("question-text");
const yesBtn = document.getElementById("yes-btn");
const pokemonImg = document.getElementById("pokemon-img");

